import intro from './intro'
import derdiedas from './der-die-das'
import eineine from './ein-eine'
import nominativ from './nominativ'
import akkusativ from './akkusativ'
import dativ from './dativ'
import daschen from './das-chen'
import derlernerdielernerin from './der-lerner-die-lernerin'
import duodersie from './du-oder-sie'
import besser from './besser'
import besten from './besten'
export default [intro, derdiedas, eineine, nominativ, daschen, akkusativ, derlernerdielernerin, duodersie, besser, besten, dativ]