import introduction from './introduction'
import derdiedas from './der-die-das'
import eineine from './ein-eine'
import sein from './sein'
import accusative from './accusative'
import dative from './dative'
import daschen from './das-chen'
import derlernerdielernerin from './der-lerner-die-lernerin'
import duodersie from './du-oder-sie'
import comparative from './comparative'
import superlative from './superlative'
import genitiv from './genitiv'
import imperativ from './imperativ'
import compoundWords from './compound-words'
import adjectiveEndings from './adjective-endings'
import ndeclension from './n-declension'
import lich from './-lich'
import ordinalnumbers from './ordinal-numbers'
import derwords from './der-words'

export default [introduction, derdiedas, eineine, sein, daschen, accusative, dative, derlernerdielernerin, duodersie, comparative, superlative, genitiv, imperativ, compoundWords, adjectiveEndings, ndeclension, lich, ordinalnumbers, derwords]