import derdiedas from './der-die-das'
import eineine from './ein-eine'
import sein from './sein'
import accusative from './accusative'
import dative from './dative'
import daschen from './das-chen'
import derlernerdielernerin from './der-lerner-die-lernerin'
import duodersie from './du-oder-sie'
import comparative from './comparative'
import superlative from './superlative'
import genitiv from './genitiv'
import imperativ from './imperativ'
import compoundWords from './compound-words'
import adjectiveEndings from './adjective-endings'

export default [derdiedas, eineine, sein, daschen, accusative, dative, derlernerdielernerin, duodersie, comparative, superlative, genitiv, imperativ, compoundWords, adjectiveEndings]